# Generated by Django 5.0.4 on 2024-06-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='data_files/')),
            ],
        ),
    ]
